// This file is generated by scripts/generateBusyboxStageIndex.mjs.
// Do not edit by hand.
import { manifest as stage0 } from "../stages/S-000/manifest";
import { manifest as stage1 } from "../stages/S-010/manifest";
import { manifest as stage2 } from "../stages/S-020/manifest";
import { manifest as stage3 } from "../stages/S-030/manifest";
import { manifest as stage4 } from "../stages/S-040/manifest";
import { manifest as stage5 } from "../stages/S-050/manifest";
import { manifest as stage6 } from "../stages/S-060/manifest";
import { manifest as stage7 } from "../stages/S-070/manifest";
import { manifest as stage8 } from "../stages/S-080/manifest";
import { manifest as stage9 } from "../stages/S-090/manifest";
import { manifest as stage10 } from "../stages/S-100/manifest";
import { manifest as stage11 } from "../stages/S-110/manifest";
import { manifest as stage12 } from "../stages/S-120/manifest";
import { manifest as stage13 } from "../stages/S-130/manifest";
import { manifest as stage14 } from "../stages/S-140/manifest";
import { manifest as stage15 } from "../stages/S-150/manifest";
import { manifest as stage16 } from "../stages/S-160/manifest";
import { manifest as stage17 } from "../stages/S-170/manifest";
import { manifest as stage18 } from "../stages/S-180/manifest";
import { manifest as stage19 } from "../stages/S-190/manifest";
import { manifest as stage20 } from "../stages/S-200/manifest";
import { manifest as stage21 } from "../stages/S-210/manifest";
import { manifest as stage22 } from "../stages/S-220/manifest";
import { manifest as stage23 } from "../stages/S-240/manifest";
import { manifest as stage24 } from "../stages/S-250/manifest";
import { manifest as stage25 } from "../stages/S-260/manifest";
import { manifest as stage26 } from "../stages/S-280/manifest";
import { manifest as stage27 } from "../stages/S-290/manifest";
import { manifest as stage28 } from "../stages/S-300/manifest";
import { manifest as stage29 } from "../stages/S-310/manifest";
import { manifest as stage30 } from "../stages/S-320/manifest";
import { manifest as stage31 } from "../stages/S-330/manifest";
import { manifest as stage32 } from "../stages/S-340/manifest";
import { manifest as stage33 } from "../stages/S-350/manifest";
import { manifest as stage34 } from "../stages/S-360/manifest";
import { manifest as stage35 } from "../stages/S-370/manifest";
import { manifest as stage36 } from "../stages/S-380/manifest";
import { manifest as stage37 } from "../stages/S-390/manifest";
import { manifest as stage38 } from "../stages/S-400/manifest";
import { manifest as stage39 } from "../stages/S-410/manifest";
import { manifest as stage40 } from "../stages/S-420/manifest";
import { manifest as stage41 } from "../stages/S-430/manifest";
import { manifest as stage42 } from "../stages/S-440/manifest";
import { manifest as stage43 } from "../stages/S-450/manifest";
import { manifest as stage44 } from "../stages/S-460/manifest";
import { manifest as stage45 } from "../stages/S-480/manifest";
import { manifest as stage46 } from "../stages/S-490/manifest";
import { manifest as stage47 } from "../stages/S-500/manifest";
import { manifest as stage48 } from "../stages/S-510/manifest";
import { manifest as stage49 } from "../stages/S-520/manifest";
import { manifest as stage50 } from "../stages/S-530/manifest";
import { manifest as stage51 } from "../stages/S-540/manifest";
import { manifest as stage52 } from "../stages/S-550/manifest";
import { manifest as stage53 } from "../stages/S-560/manifest";
import { manifest as stage54 } from "../stages/S-570/manifest";
import { manifest as stage55 } from "../stages/S-580/manifest";
import { manifest as stage56 } from "../stages/S-590/manifest";
import { manifest as stage57 } from "../stages/S-600/manifest";
import { manifest as stage58 } from "../stages/S-610/manifest";
import { manifest as stage59 } from "../stages/S-620/manifest";
import { manifest as stage60 } from "../stages/S-630/manifest";
import { manifest as stage61 } from "../stages/S-640/manifest";
import { manifest as stage62 } from "../stages/S-650/manifest";
import { manifest as stage63 } from "../stages/S-660/manifest";
import { manifest as stage64 } from "../stages/S-670/manifest";
import { manifest as stage65 } from "../stages/S-690/manifest";
import { manifest as stage66 } from "../stages/S-700/manifest";
import { manifest as stage67 } from "../stages/S-710/manifest";
import { manifest as stage68 } from "../stages/S-720/manifest";
import { manifest as stage69 } from "../stages/S-730/manifest";
import { manifest as stage70 } from "../stages/S-740/manifest";
import { manifest as stage71 } from "../stages/S-750/manifest";
import { manifest as stage72 } from "../stages/S-760/manifest";
import { manifest as stage73 } from "../stages/S-770/manifest";
import { manifest as stage74 } from "../stages/S-780/manifest";
import { manifest as stage75 } from "../stages/S-790/manifest";
import { manifest as stage76 } from "../stages/S-800/manifest";
import { manifest as stage77 } from "../stages/S-810/manifest";
import { manifest as stage78 } from "../stages/S-820/manifest";
import { manifest as stage79 } from "../stages/S-830/manifest";
import { manifest as stage80 } from "../stages/S-840/manifest";
import { manifest as stage81 } from "../stages/S-850/manifest";
import { manifest as stage82 } from "../stages/S-860/manifest";
import { manifest as stage83 } from "../stages/S-870/manifest";
import { manifest as stage84 } from "../stages/S-880/manifest";
import { manifest as stage85 } from "../stages/S-890/manifest";
import { manifest as stage86 } from "../stages/S-900/manifest";
import { manifest as stage87 } from "../stages/S-910/manifest";
import { manifest as stage88 } from "../stages/S-920/manifest";

export const stageIndex = [
  stage0,
  stage1,
  stage2,
  stage3,
  stage4,
  stage5,
  stage6,
  stage7,
  stage8,
  stage9,
  stage10,
  stage11,
  stage12,
  stage13,
  stage14,
  stage15,
  stage16,
  stage17,
  stage18,
  stage19,
  stage20,
  stage21,
  stage22,
  stage23,
  stage24,
  stage25,
  stage26,
  stage27,
  stage28,
  stage29,
  stage30,
  stage31,
  stage32,
  stage33,
  stage34,
  stage35,
  stage36,
  stage37,
  stage38,
  stage39,
  stage40,
  stage41,
  stage42,
  stage43,
  stage44,
  stage45,
  stage46,
  stage47,
  stage48,
  stage49,
  stage50,
  stage51,
  stage52,
  stage53,
  stage54,
  stage55,
  stage56,
  stage57,
  stage58,
  stage59,
  stage60,
  stage61,
  stage62,
  stage63,
  stage64,
  stage65,
  stage66,
  stage67,
  stage68,
  stage69,
  stage70,
  stage71,
  stage72,
  stage73,
  stage74,
  stage75,
  stage76,
  stage77,
  stage78,
  stage79,
  stage80,
  stage81,
  stage82,
  stage83,
  stage84,
  stage85,
  stage86,
  stage87,
  stage88,
] as const;

export type StageId = (typeof stageIndex)[number]["id"];
