import { readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dirname, "..");
const stagesDirectory = resolve(repositoryRoot, "src", "busybox", "stages");
const outputPath = resolve(
  repositoryRoot,
  "src",
  "busybox",
  "runtime",
  "stage-index.generated.ts",
);
const checkOnly = process.argv.includes("--check");

const entries = await readdir(stagesDirectory, { withFileTypes: true });
const stageDirectories = entries
  .filter((entry) => entry.isDirectory() && /^S-\d{3}$/.test(entry.name))
  .map((entry) => entry.name)
  .sort((left, right) => left.localeCompare(right));

for (const directory of stageDirectories) {
  const files = await readdir(resolve(stagesDirectory, directory));
  const missing = ["manifest.ts", "locale.ts", "stage.tsx"].filter(
    (file) => !files.includes(file),
  );
  if (missing.length > 0) {
    throw new Error(
      `${directory} must contain ${missing.join(", ")} before it can be indexed.`,
    );
  }
}

const imports = stageDirectories
  .map(
    (directory, index) =>
      `import { manifest as stage${index} } from "../stages/${directory}/manifest";`,
  )
  .join("\n");
const manifests = stageDirectories
  .map((_, index) => `  stage${index},`)
  .join("\n");
const output = `// This file is generated by scripts/generateBusyboxStageIndex.mjs.\n// Do not edit by hand.\n${imports}\n\nexport const stageIndex = [\n${manifests}\n] as const;\n\nexport type StageId = (typeof stageIndex)[number]["id"];\n`;

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      "Busybox stage index is stale. Run: node scripts/generateBusyboxStageIndex.mjs",
    );
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, output);
}
